# Generated by Django 4.1.7 on 2023-04-25 16:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_studentprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('extra_symptoms', models.TextField()),
                ('diagnose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Attended', 'Attended')], default='Pending', max_length=10)),
                ('prescription_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.prescription')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('symptoms', models.ManyToManyField(related_name='symptoms', to='appointments.symptom')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2023, 5, 9))), name='check_appointment_date_range'),
        ),
    ]
