# Generated by Django 4.1.7 on 2023-03-08 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_check_appointment_date_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='check_appointment_date_range',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription',
            field=models.TextField(null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__lt', datetime.datetime(2023, 3, 25, 17, 54, 10, 143942))), name='check_appointment_date_range'),
        ),
    ]
