# Generated by Django 4.1.7 on 2023-03-08 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_appointment_check_appointment_date_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='check_appointment_date_range',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__lt', datetime.datetime(2023, 3, 25, 23, 8, 25, 917061))), name='check_appointment_date_range'),
        ),
    ]
