# Generated by Django 4.1.7 on 2023-03-13 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_appointment_check_appointment_date_range_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='check_appointment_date_range',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='diagnose',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__lt', datetime.datetime(2023, 3, 30, 12, 41, 23, 283505))), name='check_appointment_date_range'),
        ),
    ]
