# Generated by Django 4.1.7 on 2023-04-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_remove_appointment_check_appointment_date_range_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='check_appointment_date_range',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('date__lte', datetime.date(2023, 5, 4))), name='check_appointment_date_range', violation_error_message='You Cannot book appointments more in advanced than 2 weeks.'),
        ),
    ]
